# File: .github/workflows/repo-sync.yml
name: sync-yuannian1112-scripts
on:
  schedule:
    - cron: '45 */8 * * *'
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ main ]
  repository_dispatch:
    types: sync-yuannian1112-scripts
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
      dst_key: ${{ secrets.GITEE_PRIVATE_KEY }} # 我自己同步到gitee使用，其他人可忽略
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: sync yuannian1112-scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/yuannian1112/jd_scripts.git"
          source_branch: "main"
          destination_branch: "main"
          sync_tags: "true"
          github_token: ${{ secrets.PAT }}

      - name: Merge main -> master
        uses: devmasx/merge-branch@v1.3.1
        if: env.PAT
        with:
          type: now
          from_branch: main
          target_branch: master
          github_token: ${{ secrets.PAT }}

      # 我自己同步到gitee使用，其他人可忽略
      - name: sync github -> gitee
        uses: Yikun/hub-mirror-action@master
        if: env.dst_key
        with:
          src: github/eicky
          dst: gitee/eicky
          static_list: "jd_scripts"
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          force_update: true
